feat(FX-4027): Add keyword filter to artist page's artwork grid
artsy/force pull request #10379
Opened 2022-06-23 12:42 UTC by nickskalkin

The type of this PR is: **Feature**

This PR solves [FX-4027]

### Description

2022-06-27 09:30 UTC, mdole submitted a review, later dismissed
@nickskalkin nice work! One high-level thought: since this PR doesn't include support for `keyword` in alert creation, should we put it behind a feature flag until we have a chance to complete that work (ticketed [here](https://artsyproduct.atlassian.net/browse/FX-4029))? 

It feels a bit confusing to be able to filter down to a keyword but not include it in a set alert, so my tendency would be to feature flag it for now, but could also be a good question for Mel.

2022-06-27 09:56 UTC, dimatretyak requested changes
Unfortunately, there are a couple of problems that need to be fixed for mWeb:
1. Query to Metaphysics should be executed only when the "Show Results" button has been pressed
2. "Clear all" button don't clear the keyboard search input

2022-06-27 09:56 UTC, dimatretyak commented on src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
> +  )
**suggestion**: create a separate component for this

2022-06-28 13:41 UTC, nickskalkin commented
hey @mdole @dimatretyak made changes you suggested, could you take a look?

2022-06-29 16:29 UTC, dimatretyak commented on src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
> +}
**praise**: thank you for these changes 👏

2022-06-29 16:29 UTC, dimatretyak commented on src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
> +  keyword: undefined,
**question**: can you please remind me why `keyword` is `undefined` here?

2022-06-30 09:05 UTC, dimatretyak approved these changes

2022-07-04 13:52 UTC, merged