refactor(cleanup): remove force-fetch-alert-labels-from-metaphysics ff
artsy/force pull request #12097
Opened 2023-03-16 09:29 UTC by gkartalis

The type of this PR is: **TYPE**

This PR solves [FX-4671]

### Description

remove force-fetch-alert-labels-from-metaphysics ff

2023-03-16 11:04 UTC, dimatretyak requested changes

2023-03-16 11:06 UTC, gkartalis commented
converted to Draft, will address later (switched focus to artwork lists for now)

2023-03-16 13:20 UTC, dimatretyak commented on src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
> +  pills = convertLabelsToPills(labels)
As far as I understand, we want to parse pill labels **from aggregations**, and not get pill labels from Metaphysics. If yes, then in that case we should remove the `labels` and `pills` variables and not pass `initialPills` prop [here](https://github.com/artsy/force/blob/e7abbce7896ef50fa354ea3a939a36d89219af4d/src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx#L331)

2023-03-16 13:23 UTC, dimatretyak commented on src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
> +        if (props?.artistsConnection && props.me && props.viewer) {
If we will parse pill labels from aggregations, then we have to delete [this](https://github.com/artsy/force/blob/e7abbce7896ef50fa354ea3a939a36d89219af4d/src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx#L465-L477)

2023-03-16 13:23 UTC, dimatretyak commented on src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
> +  pills = convertLabelsToPills(labels)
Addition to the previous message: https://github.com/artsy/force/pull/12097/files#r1138655901

2023-03-20 12:26 UTC, dimatretyak approved these changes

2023-03-20 13:28 UTC, merged