chore(NX-3492): change support links from ZD to Salesforce
artsy/force pull request #12274
Opened 2023-04-19 09:18 UTC by araujobarret

The type of this PR is: **Chore**

This PR solves [NX-3492]

### Description

Changes Support links from Zendesk to Salesforce.

2023-04-19 10:27 UTC, lidimayra approved these changes

2023-04-20 08:06 UTC, lidimayra commented
2 of the links added in this PR are not working as expected. These URLs are matching the ones we have in the [spreadsheet](https://docs.google.com/spreadsheets/d/1Yofy_cExeEgdV1-o8rzMrGnJ6In4c0aotV5dzowhYUU/edit#gid=571260299). I'll share this on [#zendesk-sf-migration](https://artsy.slack.com/archives/C04U9SJ5A0K) channel

- https://support.artsy.net/s/article/What-Counts-as-an-Artworks-Proof-of-Authenticity
- https://support.artsy.net/s/article/How-are-taxes-customs-VAT-and-import-fees-handled-on-works-listed-with-secure-checkout
- https://support.artsy.net/s/article/How-do-I-place-a-bid-in-an-auction
- https://support.artsy.net/s/topic/0TO3b000000UesxGAC/sell
- https://support.artsy.net/s/article/Im-an-artist-Can-I-submit-my-own-work-to-sell
- https://support.artsy.net/s/topic/s/topic/0TO3b000000UevEGAS/contacting-a-gallery ❌
- https://support.artsy.net/s/article/How-to-Complete-Identity-Verification
- https://support.artsy.net/s/topic/s/topic/0TO3b000000UevOGAS/sell-with-artsy ❌
- https://support.artsy.net/s/article/The-Artsy-Guarantee
- https://support.artsy.net/s/topic/0TO3b000000UessGAC/buy
- https://support.artsy.net/s/article/The-Complete-Guide-to-Auctions-on-Artsy

2023-04-20 08:58 UTC, lidimayra requested changes

2023-04-20 08:58 UTC, lidimayra commented on src/Apps/Conversation/Components/DetailsSidebar.tsx
> +            to="https://support.artsy.net/s/topic/s/topic/0TO3b000000UevEGAS/contacting-a-gallery"
```suggestion
            to="https://support.artsy.net/s/topic/0TO3b000000UevEGAS/contacting-a-gallery"
```

2023-04-20 08:58 UTC, lidimayra commented on src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWAHowItWorksModal.tsx
> +    "https://support.artsy.net/s/topic/s/topic/0TO3b000000UevOGAS/sell-with-artsy"
```suggestion
    "https://support.artsy.net/s/topic/0TO3b000000UevOGAS/sell-with-artsy"
```

2023-04-20 08:58 UTC, lidimayra commented on src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASectionSubmitted.tsx
> +    "https://support.artsy.net/s/topic/s/topic/0TO3b000000UevOGAS/sell-with-artsy"
```suggestion
    "https://support.artsy.net/s/topic/0TO3b000000UevOGAS/sell-with-artsy"
```

2023-04-20 08:59 UTC, lidimayra approved these changes

2023-04-20 08:59 UTC, araujobarret commented
Thanks @lidimayra, changed the broken links in https://github.com/artsy/force/pull/12274/commits/cb0c350f9ad46aed6071cfc3e6d80d2b441823d1

2023-04-20 12:32 UTC, MrSltun approved these changes
✨ 🚀

2023-04-20 13:09 UTC, merged