feat: analytic events for new search bar container
artsy/force pull request #12456
Opened 2023-05-26 13:04 UTC by rajsam003

The type of this PR is: Feat

This PR solves [FX-4780]

Tasks
- [x] New events for tracking switching between pills.
- [x] Replace old “deprecated” events with new ones. 
- [x] Make sure that all events are tracked correctly

2023-05-26 13:10 UTC, dblandin reviewed
Looking good! Left a few questions/comments.

2023-05-26 13:10 UTC, dblandin commented on src/Components/Search/NewSearch/Mobile/Overlay.tsx
> +          ? ActionType.selectedSearchSuggestionQuickNavigationItem
**suggestion**: I think this "QuickNavigationItem" refers to the (Artworks) or (Auction Results) links in Artist results and not a search result/suggestion itself. We might need to stick with these deprecated action types as I think they more accurately reflect what this event is meant to track.

2023-05-26 13:10 UTC, dblandin commented on src/Components/Search/NewSearch/NewSearchBarFooter.tsx
> +      context_module: selectedPill.analyticsContextModule,
Nice 💯

2023-05-29 11:43 UTC, dimatretyak requested changes

2023-05-29 11:43 UTC, dimatretyak commented on src/Components/Search/NewSearch/Mobile/Overlay.tsx
> +  }, [fetchCounter, options])
**blocking**: every time a component is re-rendered, `options` will return a new array and a **new** reference type. For this reason, `useUpdateEffect` will be called **every** time when component is re-rendered and the event will be tracked accordingly

2023-05-29 11:43 UTC, dimatretyak commented on src/Components/Search/NewSearch/Mobile/Overlay.tsx
> +  }, [fetchCounter, options])
and +1 to the comment from Devon

2023-05-30 11:07 UTC, dimatretyak approved these changes

2023-05-30 17:33 UTC, anandaroop approved these changes

2023-05-31 12:41 UTC, rajsam003 commented
@dblandin Thanks for rebasing it

2023-05-31 12:43 UTC, dblandin commented
No problem! I noticed the Cypress test failure and then [this PR](https://github.com/artsy/force/pull/12466) from @anandaroop so hopefully the build will pass now 🙏🏼

2023-05-31 12:46 UTC, merged