fix: refactor auction results filters
artsy/force pull request #7947
Opened 2021-07-09 13:10 UTC by tr-ann

Jira: [FX-2806](https://artsyproduct.atlassian.net/browse/FX-2806)

**The purpose of the task:** refactor mobile filters on artist auction results page

Done work:
- The filters style are the same as on other mobile surfaces (ex. artist artworks)
- The filters has staged state
- Solved are most of STRICT_NULL_CHECK errors

**The filters before:**
![image](https://user-images.githubusercontent.com/56556580/125082059-6575c080-e0cf-11eb-946b-c93fc039d391.png)

**The filters after:**
![image](https://user-images.githubusercontent.com/56556580/125082098-77576380-e0cf-11eb-9749-984d91d93d42.png)

2021-07-09 15:37 UTC, dimatretyak requested changes

2021-07-09 15:37 UTC, dimatretyak commented on src/v2/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
> +      if (filterState.pageAndCursor && filterState.pageAndCursor.page === 1) {
Maybe we can replace it with such a check?
```javascript
if (filterState.pageAndCursor?.page === 1) { ... }
```

2021-07-09 15:37 UTC, dimatretyak commented on src/v2/Apps/Artist/Routes/AuctionResults/Components/ArtistAuctionResultsCount.tsx
> +      {`Showing ${results.totalCount?.toLocaleString() || ""} results`}
```{`Showing ${results.totalCount?.toLocaleString() ?? 0} results`}```

2021-07-09 15:37 UTC, dimatretyak commented on src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/SizeFilter.tsx
> +      sizes?.push(name)
```javascript
let sizes = filters?.sizes?.slice() ?? []
if (selected) {
  sizes.push(name)
} else {
  sizes = sizes.filter(item => item !== name)
}
setFilter?.("sizes", sizes)
```

2021-07-09 15:37 UTC, dimatretyak commented on src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx
> +    } else return []
```javascript
else {
  return []
}
```

2021-07-09 15:39 UTC, dimatretyak commented on src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/AuctionHouseFilter.tsx
> +    setFilter?.("organizations", selectedOrganizations)
```javascript
let selectedOrganizations = organizations?.slice() ?? []
if (selected) {
  selectedOrganizations.push(name)
} else {
  selectedOrganizations = selectedOrganizations.filter(
    item => item !== name
  )
}
setFilter?.("organizations", selectedOrganizations)
```

2021-07-13 12:32 UTC, mdole reviewed
Really good work @tr-ann!

I think what this needs now are tests :) [this PR might be helpful](https://github.com/artsy/force/pull/5658) - the filters are now a bit out of date, but you can see how Roop implemented the tests for the first version of "apply staged filters" changes by looking at the commit history.

Let me know if there's anything I can help with!

2021-07-13 16:30 UTC, dimatretyak approved these changes

2021-07-13 16:30 UTC, dimatretyak commented
LGTM 👍

2021-07-14 09:27 UTC, mdole reviewed
@tr-ann amazing, I think this is super close to done! Last thing I think we should add: tests similar to [these ones](https://github.com/artsy/force/blob/1f7c9d258c927df17b741fd7f13f1cddb2181ce5/src/v2/Components/ArtworkFilter/__tests__/ArtworkFilterContext.jest.tsx#L168) that check the behavior of the staged filters.

2021-07-14 11:16 UTC, tr-ann commented on src/v2/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
> +  keyword?: StringifyOptions
Oh, it is my fault, I don't know how it could have happened.. I'll fix it and add test for staging filters asap, thank you!

2021-07-14 12:19 UTC, mdole approved these changes
Woohooo let's ship it! 🎉

2021-07-14 12:19 UTC, merged