feat(FX-3049): nav bar update
artsy/force pull request #7972
Opened 2021-07-14 12:47 UTC by tr-ann

Jira: [FX-3049](https://artsyproduct.atlassian.net/browse/FX-3049)

Description:
The Curatorial team is requesting an update to the Artworks and Artists Nav Bars at the top of artsy.net. We've reviewed the performance of existing categories and collections, and removed low performing content and introduced new content that has historically performed well. We're hoping that this update can take place in early Q3.

Link to requested updates: https://docs.google.com/spreadsheets/d/1EOYineDRM9QTfNE7gUyO3pnqKUrr_pgekCHYsWsxK-U/edit#gid=0

_ARTIST_
**Artist Nav Before:**
![image](https://user-images.githubusercontent.com/56556580/125620777-f8dc4222-5a78-48bf-9365-254c3c747634.png)

**Artist Nav After:**
![image](https://user-images.githubusercontent.com/56556580/125620890-a08c0b3c-a2a4-421f-870e-4b3f13e459f5.png)

_ARTWORK_
**Artwork Nav Before**
![image](https://user-images.githubusercontent.com/56556580/125620843-768e1b9d-6c34-4315-905a-0897847f8d25.png)

**Artwork Nav After**
![image](https://user-images.githubusercontent.com/56556580/125620927-fa7787d1-4805-4f0b-923e-a6078601d24c.png)

2021-07-14 15:59 UTC, dimatretyak approved these changes
LGTM 👍

2021-07-19 08:47 UTC, mdole requested changes
@tr-ann Thanks for picking this up! Two small changes (neither of which are on you - they were mistakes in the original spreadsheet) and we'll be ready to merge :)

2021-07-19 08:47 UTC, mdole commented on src/v2/Components/NavBar/menuData.ts
> +        text: "Artist's We're Eyeing",
Ah, this should actually be "Artists We're Eyeing" (it's incorrect in the spreadsheet too, but you can see on the [actual page](https://www.artsy.net/collection/artists-we-are-eyeing) how it should read)

2021-07-19 08:47 UTC, mdole commented on src/v2/Components/NavBar/menuData.ts
> +              text: "Work on Paper",
Hmmm this is a tough one...I think it should also be `Works on Paper`. Let's make that change, and I'll confirm with the team responsible

2021-07-19 09:21 UTC, tr-ann commented
@mdole thanks for the comments. I made the changes so can you review it again? :)

2021-07-19 09:22 UTC, mdole approved these changes
Perfect thanks! #squashongreen

2021-07-19 09:28 UTC, merged